sudo: false
language: python

services:
  - memcached

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3

install:
  - travis_retry pip install tox

script:
  - travis_retry tox
  - PYTHONPATH=. python pymemcache/test/integration.py -s localhost -p 11211
