language: python

services:
  - memcached

install: "pip install six"

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

script:
  - python setup.py nosetests
  - PYTHONPATH=. python pymemcache/test/integration.py -s localhost -p 11211
